### ISSUE TITLE
Write & publish 31st summary

### ISSUE THREAD

**Issue by pvzhelnov** [drzhelnov/zheln.github.io#206]
Zhelnov P. `title`. Zheln. 2021 Oct 20;Suppl:s31e`edition`. URI: https://zheln.com/summary/2021/10/20/1/.

Patreon, Open Collective, Twitter Personal, Instagram, Facebook Personal, Telegram

**Comment by pussiatoday** [comment]
Thought it over and decided to use continued numeration of volumes to avoid inconsistencies with week numbers.
